Models/Department.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
#nullable disable

namespace PoliceWebApplication
{
    public partial class Department
    {
        public Department()
        {
            Investigators = new HashSet<Investigator>();
        }

        public int Id { get; set; }
        [Display(Name = "Вулиця")]
        public int StreetId { get; set; }
        [Display(Name ="Будинок")]
        [Required(ErrorMessage = "Введіть, будь ласка, номер будинку")]
        [Range(1, Int32.MaxValue, ErrorMessage = "Введіть, будь ласка, номер будинку")]
        public int House { get; set; }
        [Display(Name = "Вулиця")]
        public virtual Street Street { get; set; }
        public virtual ICollection<Investigator> Investigators { get; set; }
    }
}

Controllers/DepartmentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PoliceWebApplication;

using Microsoft.AspNetCore.Http;
using System.IO;
using ClosedXML.Excel;
using Microsoft.AspNetCore.Authorization;

namespace PoliceWebApplication.Controllers
{
    public class DepartmentsController : Controller
    {
        private readonly DBPoliceContext _context;

        public DepartmentsController(DBPoliceContext context)
        {
            _context = context;
        }

        [Authorize(Roles = "admin, user")]
        // GET: Departments
        public async Task<IActionResult> Index(int? id, string? name)
        {
            if (id == null) return RedirectToAction("Index", "Streets");

            ViewBag.StreetId = id;
            ViewBag.StreetName = name;
            var departmentByStreet = _context.Departments.Where(b => b.StreetId == id).Include(b => b.Street);
            return View(await departmentByStreet.ToListAsync());
        }
        //  GET: Departments/Return
        public IActionResult Return(int streetId)
        {
            int cityId = _context.Streets.Where(s => s.Id == streetId).FirstOrDefault().CityId;
            return RedirectToAction("Index", "Streets", new
            {
                id = cityId,
                name = _context.Cities.Where(c => c.Id == cityId).FirstOrDefault().Name
            }) ;
        }

        [Authorize(Roles = "admin, user")]
        public ActionResult Export(int streetId)
        {
            using (XLWorkbook workbook = new XLWorkbook(XLEventTracking.Disabled))
            {
                var departments = _context.Departments.Include("Investigators").Where(c => c.StreetId == streetId).ToList();
                //тут, для прикладу ми пишемо усі книжки з БД, в своїх проектах ТАК НЕ РОБИТИ (писати лише вибрані) DONE
                foreach (var c in departments)
                {
                    var worksheet = workbook.Worksheets.Add(c.Id.ToString());

                    worksheet.Cell("A1").Value = "Ім'я";
                    worksheet.Cell("B1").Value = "Дата народження";
                    worksheet.Cell("C1").Value = "Характеристика";
                    //worksheet.Cell("D1").Value = "Справи:";
                    worksheet.Row(1).Style.Font.Bold = true;
                    var investigators = c.Investigators.ToList();

                    //нумерація рядків/стовпчиків починається з індекса 1 (не 0)
                    for (int i = 0; i < investigators.Count; i++)
                    {
                        worksheet.Cell(i + 2, 1).Value = investigators[i].Name;
                        worksheet.Cell(i + 2, 2).Value = investigators[i].DateOfBirth;
                        worksheet.Cell(i + 2, 3).Value = investigators[i].Characteristic;
                        /*
                        var invcases = _context.Cases.Where(a => a.InvestigatorId == investigators[i].Id).ToList();
                        //більше 4-ох нікуди писати NO
                        int j = 0;
                        foreach (var cas in invcases)
                        {
                            {
                                worksheet.Cell(i + 2, j + 4).Value = cas.Id;
                                j++;
                            }
                        }
                        */
                    }
                }
                using (var stream = new MemoryStream())
                {
                    workbook.SaveAs(stream);
                    stream.Flush();

                    return new FileContentResult(stream.ToArray(),
                        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")
                    {
                        FileDownloadName = $"PoliceWebApp_Street{streetId}.xlsx"
                    };
                }
            }
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin, user")]
        public async Task<IActionResult> Import(IFormFile fileExcel, int streetId)
        {
            if (ModelState.IsValid)
            {
                if (fileExcel != null)
                {
                    using (var stream = new FileStream(fileExcel.FileName, FileMode.Create))
                    {
                        await fileExcel.CopyToAsync(stream);
                        using (XLWorkbook workBook = new XLWorkbook(stream, XLEventTracking.Disabled))
                        {
                            //перегляд усіх листів (в даному випадку категорій)
                            foreach (IXLWorksheet worksheet in workBook.Worksheets)
                            {
                                //worksheet.Name - назва категорії. Пробуємо знайти в БД, якщо відсутня, то створюємо нову
                                Department newdept;
                                var d = (from dept in _context.Departments
                                         where dept.Id == Int32.Parse(worksheet.Name)
                                         select dept).ToList();
                                if (d.Count > 0)
                                {
                                    newdept = d[0];
                                }
                                else
                                {
                                    newdept = new Department();
                                    newdept.Id = Int32.Parse(worksheet.Name);
                                    newdept.StreetId = streetId;
                                    newdept.House = 9999999;
                                    //додати в контекст
                                    _context.Departments.Add(newdept);
                                }
                                //перегляд усіх рядків                    
                                foreach (IXLRow row in worksheet.RowsUsed().Skip(1))
                                {
                                    try
                                    {
                                        Investigator investigator = new Investigator();
                                        investigator.Name = row.Cell(1).Value.ToString();
                                        investigator.DateOfBirth = DateTime.Parse(row.Cell(2).Value.ToString());
                                        investigator.Characteristic = row.Cell(3).Value.ToString();
                                        investigator.Department = newdept;


                                        var cloneInv = (from inv in _context.Investigators
                                                        where inv.Name == investigator.Name && inv.DateOfBirth == investigator.DateOfBirth && inv.Characteristic == investigator.Characteristic
                                                        select inv).ToList();
                                        if(cloneInv.Count == 0)
                                        _context.Investigators.Add(investigator);

                                        /*
                                        //у разі наявності автора знайти його, у разі відсутності - додати
                                        for (int i = 4; i <= 999999; i++)
                                        {
                                            if (row.Cell(i).Value.ToString().Length > 0)
                                            {
                                                Case cas;

                                                var casss = (from cass in _context.Cases
                                                         where cass.Id == Int32.Parse(row.Cell(i).Value.ToString())
                                                         select cass).ToList();
                                                if (casss.Count > 0)
                                                {
                                                    cas = casss[0];
                                                }
                                                else
                                                {
                                                    cas = new Case();
                                                    cas.Id = Int32.Parse(row.Cell(i).Value.ToString());
                                                    cas.Info = "from EXCEL";
                                                    //додати в контекст
                                                    _context.Cases.Add(cas);
                                                }
                                            }
                                        }
                                        */
                                    }
                                    catch (Exception e)
                                    {
                                        //logging самостійно :)

                                    }
                                }
                            }
                        }
                    }
                }

                await _context.SaveChangesAsync();
            }
            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = "admin, user")]
        // GET: Departments/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var department = await _context.Departments
                .Include(d => d.Street)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (department == null)
            {
                return NotFound();
            }

            return RedirectToAction("Index", "Investigators", new { id = department.Id, house = department.House });
            //return View(department);
        }


        [Authorize(Roles = "admin")]
        // GET: Departments/Create

Controllers/RolesController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using PoliceWebApplication.Models;
using PoliceWebApplication.Models.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;

namespace PoliceWebApplication.Controllers
{
    [Authorize(Roles = "admin")]
    public class RolesController : Controller
    {
        RoleManager<IdentityRole> _roleManager;
        UserManager<User> _userManager;
        public RolesController(RoleManager<IdentityRole> roleManager, UserManager<User> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }
        public IActionResult Index() => View(_roleManager.Roles.ToList());
        public IActionResult UserList() => View(_userManager.Users.ToList());

        public async Task<IActionResult> Edit(string userId)
        {
            // отримуємо користувача
            User user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                //список ролей користувача
                var userRoles = await _userManager.GetRolesAsync(user);
                var allRoles = _roleManager.Roles.ToList();
                ChangeRoleViewModel model = new ChangeRoleViewModel
                {
                    UserId = user.Id,
                    UserEmail = user.Email,
                    UserRoles = userRoles,
                    AllRoles = allRoles
                };
                return View(model);
            }

            return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> Edit(string userId, List<string> roles)
        {
            // отримуємо користувача
            User user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                // список ролей користувача
                var userRoles = await _userManager.GetRolesAsync(user);
                // получаем все роли
                var allRoles = _roleManager.Roles.ToList();
                // список ролей, які було додано
                var addedRoles = roles.Except(userRoles);
                // список ролей, які було видалено
                var removedRoles = userRoles.Except(roles);

                await _userManager.AddToRolesAsync(user, addedRoles);

                await _userManager.RemoveFromRolesAsync(user, removedRoles);

                return RedirectToAction("UserList");
            }

            return NotFound();
        }
    }
}

Views/Departments/Create.cshtml
@model PoliceWebApplication.Department

@{
    ViewData["Title"] = "Додати відділок";
}

<h1><img src="~/css/police.png" width="100" height="100"> Додати відділок на вулиці @ViewBag.StreetName</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type = "hidden" value = "@ViewBag.StreetId" name = "StreetId"/>
            @*
        <div class="form-group">
            <label asp-for="StreetId" class="control-label"></label>
            <select asp-for="StreetId" class ="form-control" asp-items="ViewBag.StreetId"></select>
        </div>
            *@
            <div class="form-group">
                <label asp-for="House" class="control-label"></label>
                <input asp-for="House" class="form-control" />
                <span asp-validation-for="House" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Додати" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    @Html.ActionLink("Назад", "Index", new { id = ViewBag.StreetId, name = ViewBag.StreetName})
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Departments/Delete.cshtml
@model PoliceWebApplication.Department

@{
    ViewData["Title"] = "Видалити відділок на вулиці";
}

<h1><img src="~/css/police.png" width="100" height="100"> Видалити відділок на вулиці @ViewBag.StreetName</h1>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.House)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.House)
        </dd>
        @*
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Street)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Street.Name)
        </dd class>
        *@
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="hidden" value="@ViewBag.StreetId" name="streetId" />
        <input type="submit" value="Видалити" class="btn btn-danger" /> |
        @Html.ActionLink("Назад", "Index", new { id = ViewBag.StreetId, name = ViewBag.StreetName })
    </form>
</div>

Views/Departments/Details.cshtml
@model PoliceWebApplication.Department

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Department</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.House)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.House)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Street)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Street.Name)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Departments/Edit.cshtml
@model PoliceWebApplication.Department

@{
    ViewData["Title"] = "Змінити відділок";
}

<h1><img src="~/css/police.png" width="100" height="100"> Змінити відділок на вулиці @ViewBag.StreetName</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" value="@ViewBag.StreetId" name="StreetId" />
            <input type="hidden" asp-for="Id" />


            @*
        <div class="form-group">
            <label asp-for="StreetId" class="control-label"></label>
            <select asp-for="StreetId" class="form-control" asp-items="ViewBag.StreetId"></select>
            <span asp-validation-for="StreetId" class="text-danger"></span>
        </div>
            *@
            <div class="form-group">
                <label asp-for="House" class="control-label"></label>
                <input asp-for="House" class="form-control" />
                <span asp-validation-for="House" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Зберегти" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    @Html.ActionLink("Назад", "Index", new { id = ViewBag.StreetId, name = ViewBag.StreetName})
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Departments/Index.cshtml
@model IEnumerable<PoliceWebApplication.Department>

@{
    ViewData["Title"] = "Відділки за вулицею";
}

<h1><img src="~/css/police.png" width="100" height="100"> Відділки на вулиці  @ViewBag.StreetName </h1>

@if (User.IsInRole("admin"))
{
    <a><font color="red">Адміністратор</font></a>
}
else if (User.IsInRole("user"))
{
    <a><font color="blue">Користувач</font></a>
}
<p>@User.Identity.Name</p>

<form method="post" asp-controller="Account" asp-action="Logout">
    <input type="submit" value="Вихід" />
</form>

@if (User.IsInRole("admin"))
{
    <div align="right">
        <p><a class="btn btn-sm btn-outline-primary" asp-controller="Roles" asp-action="UserList">Керування користувачами</a></p>
    </div>
}
@if (User.IsInRole("admin"))
{
    <p>
        @Html.ActionLink("Додати новий відділок", "Create", new { streetId = @ViewBag.StreetId })
    </p>
}
<p>
    @Html.ActionLink("Назад", "Return", new { streetId = ViewBag.StreetId })
</p>

@if (User.IsInRole("admin"))
{
    <div>
        <h5>Оберіть exel-файл для заватаження</h5>
        @using (Html.BeginForm("Import", "Departments", FormMethod.Post, new { enctype = "multipart/form-data", id = "frm-excel" }))
        {
            <div>
                Завантажте Excel-файл:
                <input type="file" name="fileExcel" id="fileExcel" />
                <input type="hidden" value="@ViewBag.StreetId" name="streetId" />
                <div>
                    <input type="submit" value="Завантажити" />
                </div>
            </div>
        }
    </div>
    <h1> </h1>
    <div>
         <h5>Завантаження інформації в файл</h5>
        <a asp-action="Export" asp-route-streetId="@ViewBag.StreetId"> Завантажити</a>
    </div>
}

<h1>    </h1>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.House)
            </th>
            @*
                <th>
                    @Html.DisplayNameFor(model => model.Street)
                </th>
            *@
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.House)
                </td>
                @*
                    <td>
                        @Html.DisplayFor(modelItem => item.Street.Name)
                    </td>
                *@
                <td>
                    @if (User.IsInRole("admin"))
                    {@Html.ActionLink("Змінити |", "Edit", new { streetId = @ViewBag.StreetId, deptId = item.Id })}

                    <a asp-action="Details" asp-route-id="@item.Id">Слідчі</a>

                    @if (User.IsInRole("admin"))
                    {@Html.ActionLink("| Видалити", "Delete", new { streetId = @ViewBag.StreetId, deptId = item.Id })}
                </td>
            </tr>
        }
    </tbody>
</table>